run:
  concurrency: 4
  timeout: 3m
  tests: false
  skip-dirs:
    - app/generated
    - app/repository/mocks
  skip-files:
    - ".*easyjson\\.go$"
    - "mock_.*\\.go$"
    - ".*_mock\\.go$"

output:
  format: colored-line-number
  print-issued-lines: false

issues:
  new-from-rev: 05.04.22

linters-settings:
  lll:
    line-length: 120

  goimports:
    local-prefixes: "outboxer"

  gomnd:
    ignored-numbers:
      - '0'
    ignored-functions:
      - 'strings.*'
      - 'strconv.*'

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - asciicheck
    - makezero
    - nestif
    - prealloc
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    #    - usestdlibvars
    - promlinter
